title: /dev/kraluk
# email: sample@mail.com
description: > # this means to ignore newlines until "baseurl:"
  Just my blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kraluk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lkrauzo
github_username:  kraluk

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
